### ISSUE TITLE
Limit avatar file sizes

### ISSUE THREAD

**Issue by felixoi** [SpongePowered/SpongeAuth#158]
As mentioned in https://github.com/SpongePowered/Ore/issues/475 some avatar files are far to big. We need to limit this somehow and have to think about how to get rid of the big ones.

**Comment by lukegb** [comment]
I'd rather just know what size you're expecting avatars to be, so I can scale appropriately, to be honest

**Comment by simon816** [comment]
From a quick look at discourse it looks like they have a default max size of 120x120px, which seems reasonable for an avatar size.

**Comment by lukegb** [comment]
Cool, so just request that they be sized at 120x120 ;)

**Comment by felixoi** [comment]
So can we get 120x120 as default on pingback?
