### ISSUE TITLE
QR Code Broken

### ISSUE THREAD

**Issue by felixoi** [SpongePowered/SpongeAuth#159]
Trying to add 2FA to my account but my QR-Code is broken.

[![https://gyazo.com/dc4fe0caa2ac2087f5da40e23e5b7327](https://i.gyazo.com/dc4fe0caa2ac2087f5da40e23e5b7327.png)](https://gyazo.com/dc4fe0caa2ac2087f5da40e23e5b7327)

**Comment by tylerbucher** [comment]
Ran into this today as well, just a minor inconvenience to input the code instead of scanning.
