### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by Owexz** [SpongePowered/SpongeAuth#172]
In order to comply with the upcoming EU General Data Protection Regulation, we must implement a checkbox (off-by-default) asking users the following question:

Do you agree to the use of your data in accordance with our Terms of Service, Privacy Policy and Ore Guidelines?
ToS: https://docs.spongepowered.org/stable/en/about/tos.html
Privacy Policy: https://docs.spongepowered.org/stable/en/about/privacy.html
Ore Guidelines: https://docs.spongepowered.org/stable/en/ore/guidelines.html

**Comment by progwml6** [comment]
This must also be exposed in the pingbacks/apis for ore to be able to lock out actions if the flag is not set for a user

**Comment by felixoi** [comment]
Do we still need it in pingback @progwml6?

**Comment by progwml6** [comment]
since we wiped out the sessions before GDPR came into force, no
