### ISSUE TITLE
Authentication on mobile appears to be broken

### ISSUE THREAD

**Issue by windy1** [SpongePowered/SpongeAuth#19]
With a Galaxy S7 - Chrome I consistently get

> 500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

**Comment by lukegb** [comment]
Hmm, can't reproduce on my phone for my account. I assume this doesn't happen if you log out on desktop?

Does this happen even in an incognito tab? Maybe a different phone (if you have access to one) or the Android emulator?
