### ISSUE TITLE
Ability for an Organization to change avatar

### ISSUE THREAD

**Issue by Ewoutvans** [SpongePowered/SpongeAuth#211]
- for Ore we need a way to change the Avatar (URL, Upload, Reset)

**Comment by lukegb** [comment]
* Ore requests https://auth.spongepowered.org/api/users/<org_username>/change-avatar-token/ - POST, with API key, payload includes "request_username" which is the username of the actual person who'll be doing the username change
* Auth returns a JSON blob - the key you care about is 'signed_data', which is a string
* Ore redirects the user to https://auth.spongepowered.org/accounts/user/<org_username>/change-avatar/?key=<signed_data> - where they can change the org's avatar
