### ISSUE TITLE
Does not log me in to forum and gives me multiple errors completing actions there

### ISSUE THREAD

**Issue by parlough** [SpongePowered/SpongeAuth#25]
I changed my password the other day and re-enabled two-factor authentication the other day. As a result I had to re-log in. So I did so on https://auth.spongepowered.org but now when I try to access the forums, I am not logged in there, and I get multiple errors, for example an HTTP error 500 occurs sometimes when I click on things(sometimes once and sometimes more than once). After one of these errors occurs, it occurs on multiple pages, not allowing me to even read the forums. Some actions hang for an extended period of time as well, especially if an error is about to occur. 

![image](https://cloud.githubusercontent.com/assets/18372958/23343793/95858b02-fc36-11e6-80a8-85aa80535b6b.png)

**Comment by parlough** [comment]
I am logged into Auth and Ore just fine though.

**Comment by lukegb** [comment]
Yeah, that's a Discourse bug I haven't worked out yet.

If you clear your cookies (sorry!) then it should work fine.

**Comment by lukegb** [comment]
Scratch that, think I've figured it out.

**Comment by parlough** [comment]
I tried to clear all browser data a few times and it didn't work unfortunately.

**Comment by parlough** [comment]
This also occurs on my phone and I get access denied issues fairly often.

**Comment by lukegb** [comment]
I did a stupid. I figured it out and didn't apply the change in the correct place.

This'll get rolled up into the next Discourse deploy.

**Comment by parlough** [comment]
Okay cool, appreciate the fast response.

**Comment by parlough** [comment]
@lukegb Unfortunately this still seems to be occurring, even after I completely deleted my browser cache. It still does not let me log into the forums, Instead now though I'm getting "You must be logged in to do this" or an nginx "504 Gateway Timeout Error" which persists for a while.
