### ISSUE TITLE
Cache avatars

### ISSUE THREAD

**Issue by Katrix** [SpongePowered/SpongeAuth#256]
Currently, there are no caching headers for avatars. This means that the Ore homepage loads much slower than it needs to. We have currently implemented this in a basic form for project icons on Ore. Now we just need it from the Auth side too.

**Comment by lukegb** [comment]
Added some headers I think are reasonable. It would be nice to support must-revalidate so people can change avatars quickly, but I also don't think 5 minutes of expiry is unreasonable.
