### ISSUE TITLE
Unbreak the Spongie graphic at the bottom

### ISSUE THREAD

**Issue by lukegb** [SpongePowered/SpongeAuth#4]
It's supposed to be grey until hovered, but I broke the svg.js stuff so at the moment it's just always yellow.

**Comment by windy1** [comment]
https://github.com/SpongePowered/SpongeAuth/blob/master/public/javascripts/spongie.js
https://github.com/SpongePowered/SpongeAuth/blob/master/public/javascripts/svg.js

all you need
